# Generated by Django 5.0.7 on 2024-08-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_activw_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgurl',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
